### ISSUE TITLE
Meshview not currently working in Firefox 111.0.1

### ISSUE THREAD

**Issue by PolarBean** [Neural-Systems-at-UIO/MeshView-for-Brain-Atlases#42]
accessing the following link in firefox doesnt render any meshes but used to https://meshview.apps.hbp.eu/?atlas=ABA_Mouse_CCFv3_2017_25um

Thank you in advance.

**Comment by Tevemadar** [comment]
Can't reproduce.
Started up FF, it was 111.0.1, wanted to update:
![FF111-0-1](https://user-images.githubusercontent.com/8091052/232232494-02e00c14-e1d2-4040-ae44-3785d283ad21.png)
I've let it update, still works:
![FF112-0](https://user-images.githubusercontent.com/8091052/232232497-ce5146f9-7117-45dc-8062-df6577213517.png)

**Comment by PolarBean** [comment]
Thanks for checking. This isnt urgent at all and is probably just my machine. Here is the console log in case it comes up later.
![console-meshview](https://user-images.githubusercontent.com/38996929/232233117-e736c662-b775-4a14-a7af-08466a2cba11.PNG)
![Capture_meshview](https://user-images.githubusercontent.com/38996929/232233119-39e45219-cada-4982-87ee-8c3422e2207c.PNG)

**Comment by Tevemadar** [comment]
https://support.mozilla.org/en-US/questions/1398931 ?

**Comment by PolarBean** [comment]
haha I do have "privacy.resistFingerprinting"  enabled yeah. Makes sense that this breaks things

**Comment by PolarBean** [comment]
Feel free to close this
