### ISSUE TITLE
MeshView for developmental atlases

### ISSUE THREAD

**Issue by ingvildeb** [Neural-Systems-at-UIO/MeshView-for-Brain-Atlases#45]
For visualization and analysis in the DOPAMAP project, we would be interested in having MeshView versions for the developmental atlases. In particular, we have used the P14 and P28 atlases found here: Z:\HBP_Atlasing\Developmental_atlases\DeMBA_Developmental mouse brain atlas\DeMBA-v1\01_working-environment\01_Data\Resampled-reoriented-volumes_DeMBAv1-beta and would appreciate MeshView versions with these.

Additionally, it would be good to have versions where the point clouds can be cut from two sides (I have only heard of this feature from Martin / Trygve) so apologies if my description is unclear.

**Comment by Majpuc** [comment]
Issue merged: https://github.com/Neural-Systems-at-UIO/MeshView-for-Brain-Atlases/issues/52
