### ISSUE TITLE
Coordinate input in standalone is broken

### ISSUE THREAD

**Issue by Tevemadar** [Neural-Systems-at-UIO/MeshView-for-Brain-Atlases#47]

**Comment by Tevemadar** [comment]
This is supposed to be fixed now @ingrre

**Comment by Majpuc** [comment]
Just a comment. It is working fine for me on that version and those coordinates. Both Firefox and Chrome.

**Comment by Tevemadar** [comment]
I think at this point it's a cache issue with the browser. Try forcing a complete reload via pressing <kbd>Ctrl+F5</kbd> @ingrre.
